export const suggestSelectionText = [
  'How about...',
  '🤔 Hmm...',
  'You could watch...',
  'What do you say?',
  'Here\'s an option 👀',
  'Try this?',
  'Maybe this...',
  'Tickle your fancy?',
  'Yay or nay?',
  'What say you?!',
  'Perhaps...',
]


// ----------------------------------------------------------
// Not using this, but keeping a record for now in this file.
const categoriesList = [
  // Television
  {
    title: 'TV',
    top_level_category: true,
    type: null,
    value: null,
    icon: 'television-classic',
    iconType: 'material-community',
  },
  {
    title: 'Comedy',
    top_level_category: false,
    type: 'TV',
    value: 'tv_comedy',
    icon: 'emoticon-excited',
    iconType: 'material-community',
  },
  {
    title: 'Cooking',
    top_level_category: false,
    type: 'TV',
    value: 'tv_cooking',
    icon: 'pot',
    iconType: 'material-community',
  },
  {
    title: 'Drama',
    top_level_category: false,
    type: 'TV',
    value: 'tv_drama',
    icon: 'fire', // chili-mild
    iconType: 'material-community',
  },
  {
    title: 'Trash',
    top_level_category: false,
    type: 'TV',
    value: 'tv_trash',
    icon: 'delete-empty',
    iconType: 'material-community',
  },
  // Movies
  {
    title: 'Movies',
    top_level_category: true,
    type: null,
    value: null,
    icon: 'filmstrip',
    iconType: 'material-community',
  },
  {
    title: 'Animated',
    top_level_category: false,
    type: 'Movie',
    value: 'movie_animated',
    icon: 'clippy',
    iconType: 'material-community',
  },
  {
    title: 'Comedy',
    top_level_category: false,
    type: 'Movie',
    value: 'movie_comedy',
    icon: 'emoticon-excited',
    iconType: 'material-community',
  },
  {
    title: 'Drama',
    top_level_category: false,
    type: 'Movie',
    value: 'movie_drama',
    icon: 'fire', // chili-mild
    iconType: 'material-community',
  },
  {
    title: 'Epic Saga',
    top_level_category: false,
    type: 'Movie',
    value: 'movie_epic_saga',
    icon: 'death-star-variant',
    iconType: 'material-community',
  },
  {
    title: 'Rom-Com',
    top_level_category: false,
    type: 'Movie',
    value: 'movie_rom_com',
    icon: 'heart',
    iconType: 'material-community',
  },
  {
    title: 'Scary',
    top_level_category: false,
    type: 'Movie',
    value: 'movie_scary',
    icon: 'ghost',
    iconType: 'material-community',
  },
  {
    title: 'Suspense/Thriller',
    top_level_category: false,
    type: 'Movie',
    value: 'movie_suspense_thriller',
    icon: 'fingerprint',
    iconType: 'material-community',
  },
  {
    title: 'Vintage',
    top_level_category: false,
    type: 'Movie',
    value: 'movie_vintage',
    icon: 'video-vintage',
    iconType: 'material-community',
  },
]

export const selectionsList = [
  // TV
  {
    selection: 'tv_comedy',
    options: [
      'The Office',
      '30 Rock',
      'Parks and Recreation',
      'The Grinder',
      'Great News',
      'Unbreakable Kimmy Schmidt',
      'The Last Man on Earth',
      'Brooklyn 99',
      'The Simpsons',
      'Friends',
      'Seinfeld',
      'Santa Clarita Diet',
      'Curb Your Enthusiasm',
      'Kim\'s Convenience',
      'American Housewife',
      'The Good Place',
      'Arrested Development',
      'Daria',
    ],
  },
  {
    selection: 'tv_cooking',
    options: [
      'Chopped',
      'Worst Cooks in America',
      'Final Table',
      'Cutthroat Kitchen',
      'Nailed It',
    ],
  },
  {
    selection: 'tv_drama',
    options: [
      'Game of Thrones',
      'Lost',
      'Westworld',
      'The Blacklist',
      'Sherlock',
      'Jessica Jones',
      'Making a Murderer',
    ],
  },
  {
    selection: 'tv_trash',
    options: [
      'Back with the Ex',
      'Dance Moms',
      'The Kardashians',
    ],
  },
  // MOVIES
  {
    selection: 'movie_animated',
    options: [
      'Up',
      'Inside Out',
      'Toy Story',
      'Toy Story 2',
      'Toy Story 3',
      'Coco',
      'The Incredibles',
      'Incredibles 2',
      'Finding Nemo',
      'Finding Dory',
      'Wall-E',
      'Ratatouille',
      'Moana',
      'Zootopia',
      'Despicable Me',
      'Despicable Me 2',
      'Despicable Me 3',
      'The Lion King',
      'The Jungle Book',
      'The Aristocats',
      'The Lady and the Tramp',
    ],
  },
  {
    selection: 'movie_comedy',
    options: [
      'The Birdcage',
      'Mrs. Doubtfire',
      'Money Pit',
      'Beverly Hills Troop',
    ],
  },
  {
    selection: 'movie_drama',
    options: [
      'Jumanji',
    ],
  },
  {
    selection: 'movie_epic_saga',
    options: [
      'The Hobbit: An Unexpected Journey',
      'The Hobbit: The Battle of the Five Armies',
      'The Hobbit: The Desolation of Smaug',
      'The Lord of the Rings: The Fellowship of the Ring',
      'The Lord of the Rings: The Two Towers',
      'The Lord of the Rings: The Return of the King',
      'Star Wars: Episode I - The Phantom Menace',
      'Star Wars: Episode II - Attack of the Clones',
      'Star Wars: Episode III - Revenge of the Sith',
      'Star Wars: A New Hope',
      'Star Wars: The Empire Strikes Back',
      'Star Wars: Return of the Jedi',
      'Star Wars: The Force Awakens',
      'Star Wars: The Last Jedi',
      'Rogue One: A Star Wars Story',
      'Solo: A Star Wars Story',
      'Willow',
      'Batman Begins',
      'The Dark Knight',
      'The Dark Knight Rises',
      'Back to the Future',
      'Back to the Future Part II',
      'Back to the Future Part III',
    ],
  },
  {
    selection: 'movie_rom_com',
    options: [
      'You\'ve Got Mail',
      'Sleepless in Seattle',
      'When Harry Met Sally',
      'Love Actually',
      'How to Lose a Guy in 10 Days',
      '10 Things I Hate About You',
      'Bridget Jones\'s Diary',
      'Pretty Woman',
      'Clueless',
      'Four Weddings and Funeral',
      'The Proposal',
      '13 Going on 30',
      'The Princess Bride',
      'The Bick Sick',
      '50 First Dates',
      'The Wedding Singer',
      'There\'s Something About Mary',
      'Hitch',
      '27 Dresses',
      'My Big Fat Greek Wedding',
      'Sweet Home Alabama',
      'He\'s Just Not That into You',
      'Forgetting Sarah Marshall',
      'Bridesmaids',
    ],
  },
  {
    selection: 'movie_scary',
    options: [
      'Bird Box',
      'Silence of the Lambs',
      'Hocus Pocus',
      'The Shining',
      'The Ring',
    ],
  },
  {
    selection: 'movie_suspense_thriller',
    options: [
      'Memento',
      'The Usual Suspects',
      '12 Monkeys',
      'Minority Report',
      'The Prestige',
    ],
  },
  {
    selection: 'movie_vintage',
    options: [
      'High Society',
      'My Fair Lady',
      'To Kill a Mockingbird',
      'Roman Holiday',
      'It\'s a Wonderful Life',
      'The Wizard of Oz',
      'Pride and Prejudice',
    ],
  },
]